---
- name: Retrieve Vault Secret(s)
  hosts: localhost
  gather_facts: no

  pre_tasks:
  - name: Install hvac
    ansible.builtin.pip:
      name:
        - hvac

  tasks:
  - ansible.builtin.debug:
      msg: "{{ lookup('community.hashi_vault.vault_read', *vault_secret_paths, auth_method=vault_auth_method, username=vault_username, password=vault_password, namespace=vault_namespace, url=vault_url) }}"
    register: secret

  - ansible.builtin.debug:
      msg: "{{ item.data.data }}"
    loop: "{{ secret.msg }}"
